In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
from math import pi

In [2]:
pd.set_option('display.max_columns', None)
data = pd.read_csv('Filipino Family Income and Expenditure.csv')
data.head()

,Total Household Income,Region,Total Food Expenditure,Main Source of Income,Agricultural Household indicator,Bread and Cereals Expenditure,Total Rice Expenditure,Meat Expenditure,Total Fish and marine products Expenditure,Fruit Expenditure,Vegetables Expenditure,Restaurant and hotels Expenditure,Alcoholic Beverages Expenditure,Tobacco Expenditure,"Clothing, Footwear and Other Wear Expenditure",Housing and water Expenditure,Imputed House Rental Value,Medical Care Expenditure,Transportation Expenditure,Communication Expenditure,Education Expenditure,Miscellaneous Goods and Services Expenditure,Special Occasions Expenditure,Crop Farming and Gardening expenses,Total Income from Entrepreneurial Acitivites,Household Head Sex,Household Head Age,Household Head Marital Status,Household Head Highest Grade Completed,Household Head Job or Business Indicator,Household Head Occupation,Household Head Class of Worker,Type of Household,Total Number of Family members,Members with age less than 5 year old,Members with age 5 - 17 years old,Total number of family members employed,Type of Building/House,Type of Roof,Type of Walls,House Floor Area,House Age,Number of bedrooms,Tenure Status,Toilet Facilities,Electricity,Main Source of Water Supply,Number of Television,Number of CD/VCD/DVD,Number of Component/Stereo set,Number of Refrigerator/Freezer,Number of Washing Machine,Number of Airconditioner,"Number of Car, Jeep, Van",Number of Landline/wireless telephones,Number of Cellular phone,Number of Personal Computer,Number of Stove with Oven/Gas Range,Number of Motorized Banca,Number of Motorcycle/Tricycle
0,480332,CAR,117848,Wage/Salaries,0,42140,38300,24676,16806,3325,13460,3000,0,0,4607,63636,30000,3457,4776,2880,36200,34056,7200,19370,44370,Female,49,Single,Teacher Training and Education Sciences Programs,With Job/Business,General elementary education teaching professi...,Worked for government/government corporation,Extended Family,4,0,1,1,Single house,"Strong material(galvanized,iron,al,tile,concre...",Strong,80,75,3,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,1,0,1,1,0,0,0,2,1,0,0,1
1,198235,CAR,67766,Wage/Salaries,0,17329,13008,17434,11073,2035,7833,2360,960,2132,8230,41370,27000,3520,12900,5700,29300,9150,1500,0,0,Male,40,Married,Transport Services Programs,With Job/Business,Transport conductors,Worked for private establishment,Single Family,3,0,1,2,Single house,"Strong material(galvanized,iron,al,tile,concre...",Strong,42,15,2,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,1,1,0,1,0,0,0,3,1,0,0,2
2,82785,CAR,61609,Wage/Salaries,1,34182,32001,7783,2590,1730,3795,4545,270,4525,2735,14340,7200,70,324,420,425,6450,500,0,0,Male,39,Married,Grade 3,With Job/Business,Farmhands and laborers,Worked for private establishment,Single Family,6,0,4,3,Single house,"Light material (cogon,nipa,anahaw)",Light,35,12,1,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, shared with o...",0,"Shared, faucet, community water system",0,0,0,0,0,0,0,0,0,0,0,0,0
3,107589,CAR,78189,Wage/Salaries,0,34030,28659,10914,10812,690,7887,6280,480,0,1390,16638,6600,60,6840,660,300,3762,500,15580,15580,Male,52,Married,Elementary Graduate,With Job/Business,Rice farmers,Employer in own family-operated farm or business,Single Family,3,0,3,2,Single house,"Light material (cogon,nipa,anahaw)",Light,30,15,1,Own or owner-like possession of house and lot,Closed pit,1,"Own use, faucet, community water system",1,0,0,0,0,0,0,0,1,0,0,0,0
4,189322,CAR,94625,Wage/Salaries,0,34820,30167,18391,11309,1395,11260,6400,1040,0,4620,31122,16800,140,6996,2100,0,8472,1000,18887,75687,Male,65,Married,Elementary Graduate,With Job/Business,General managers/managing proprietors in trans...,Self-employed wihout any employee,Single Family,4,0,0,2,Single house,"Light material (cogon,nipa,anahaw)",Quite Strong,54,16,3,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,0,0,1,0,0,0,0,3,0,0,0,1

In [3]:
data.columns = data.columns.str.replace(' ', '')
data.columns = data.columns.str.replace(',', '')
data.columns = data.columns.str.replace('/', '')
data.columns = data.columns.str.replace('-', '')
data.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,NumberofTelevision,NumberofCDVCDDVD,NumberofComponentStereoset,NumberofRefrigeratorFreezer,NumberofWashingMachine,NumberofAirconditioner,NumberofCarJeepVan,NumberofLandlinewirelesstelephones,NumberofCellularphone,NumberofPersonalComputer,NumberofStovewithOvenGasRange,NumberofMotorizedBanca,NumberofMotorcycleTricycle
0,480332,CAR,117848,Wage/Salaries,0,42140,38300,24676,16806,3325,13460,3000,0,0,4607,63636,30000,3457,4776,2880,36200,34056,7200,19370,44370,Female,49,Single,Teacher Training and Education Sciences Programs,With Job/Business,General elementary education teaching professi...,Worked for government/government corporation,Extended Family,4,0,1,1,Single house,"Strong material(galvanized,iron,al,tile,concre...",Strong,80,75,3,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,1,0,1,1,0,0,0,2,1,0,0,1
1,198235,CAR,67766,Wage/Salaries,0,17329,13008,17434,11073,2035,7833,2360,960,2132,8230,41370,27000,3520,12900,5700,29300,9150,1500,0,0,Male,40,Married,Transport Services Programs,With Job/Business,Transport conductors,Worked for private establishment,Single Family,3,0,1,2,Single house,"Strong material(galvanized,iron,al,tile,concre...",Strong,42,15,2,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,1,1,0,1,0,0,0,3,1,0,0,2
2,82785,CAR,61609,Wage/Salaries,1,34182,32001,7783,2590,1730,3795,4545,270,4525,2735,14340,7200,70,324,420,425,6450,500,0,0,Male,39,Married,Grade 3,With Job/Business,Farmhands and laborers,Worked for private establishment,Single Family,6,0,4,3,Single house,"Light material (cogon,nipa,anahaw)",Light,35,12,1,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, shared with o...",0,"Shared, faucet, community water system",0,0,0,0,0,0,0,0,0,0,0,0,0
3,107589,CAR,78189,Wage/Salaries,0,34030,28659,10914,10812,690,7887,6280,480,0,1390,16638,6600,60,6840,660,300,3762,500,15580,15580,Male,52,Married,Elementary Graduate,With Job/Business,Rice farmers,Employer in own family-operated farm or business,Single Family,3,0,3,2,Single house,"Light material (cogon,nipa,anahaw)",Light,30,15,1,Own or owner-like possession of house and lot,Closed pit,1,"Own use, faucet, community water system",1,0,0,0,0,0,0,0,1,0,0,0,0
4,189322,CAR,94625,Wage/Salaries,0,34820,30167,18391,11309,1395,11260,6400,1040,0,4620,31122,16800,140,6996,2100,0,8472,1000,18887,75687,Male,65,Married,Elementary Graduate,With Job/Business,General managers/managing proprietors in trans...,Self-employed wihout any employee,Single Family,4,0,0,2,Single house,"Light material (cogon,nipa,anahaw)",Quite Strong,54,16,3,Own or owner-like possession of house and lot,"Water-sealed, sewer septic tank, used exclusiv...",1,"Own use, faucet, community water system",1,0,0,1,0,0,0,0,3,0,0,0,1

In [4]:
data['HouseholdHeadClassofWorker'].fillna('Unemployed', inplace=True)
data['HouseholdHeadOccupation'].fillna('Unemployed', inplace=True)

## ================================================================================

In [5]:
data['TotalHouseholdIncome_monthly'] = data['TotalHouseholdIncome']/12

In [6]:
target = 'TotalHouseholdIncome_monthly'
var = 'HouseholdHeadOccupation' 
a = data[var].astype('category').cat.categories
b = {i:data[data[var]==i][target].mean() for i in a}
b = sorted(b.items(), key=lambda kv: kv[1], reverse=True)
d = [i for i in b[:127]]
a = [i[0] for i in d]
c = [i[1] for i in d]

In [12]:
b

[('Aircraft pilots, navigators and flight engineers', 174160.91666666666),
 ('Medical doctors', 136525.2125),
 ('Lawyers', 117127.60294117648),
 ('Research and development managers', 114036.58333333333),
 ('Chemical engineers', 103940.11111111112),
 ('Directors and chief executives of corporations', 103506.91358024691),
 ('Government social benefits officials', 98310.16666666667),
 ('Commanding officers', 97649.29166666667),
 ('Stenographers and typists', 97155.22916666667),
 ('Dentists', 94035.33333333334),
 ('Mechanical engineers', 87642.69871794872),
 ('Government administrators (including career executive service officers)',
  86658.30277777779),
 ('Agronomists and related scientists', 85178.375),
 ('Officers, n. e. c.', 84245.08333333333),
 ('Maritime transport service supervisors', 83125.0),
 ('Production and operations managers in transport, storage and communications',
  82033.40277777777),
 ('Physiotherapists', 79767.91666666667),
 ('School supervisors and principals', 79742.26041666666),
 ('Justices', 77573.47916666667),
 ('Air transport service supervisors', 77203.33333333334),
 ('Fashion and other models', 75897.70833333334),
 ('Professional, technical and related officers', 73979.22916666667),
 ('Production and operations managers in construction', 72426.13333333333),
 ('Finance and administration managers', 71932.89393939394),
 ('Personnel and industrial relations managers', 70284.03333333333),
 ('Computer engineers and related professionals', 69321.3125),
 ('Town planners and related professionals', 68656.62499999999),
 ('Police inspectors and detectives', 68249.83854166666),
 ('School principals', 67734.28682170543),
 ('Production and operations managers in restaurant and hotels', 67090.375),
 ('Other business services and trade brokers', 66626.88888888889),
 ('Other specialized managers', 66161.50000000001),
 ('Power production plant operators', 66030.66666666667),
 ('Prison guards', 65829.14743589744),
 ('Civil engineers', 65726.42333333334),
 ('Systems analysts and designers', 65352.805555555555),
 ('Glass and ceramics kiln and related machine operators', 65035.75),
 ('Production and operations managers in business services',
  65010.113095238084),
 ('Architects', 64803.13541666666),
 ('Nutritionists-dietitians', 64313.5),
 ('Industrial engineers', 63186.791666666664),
 ('Other social science professionals', 63131.16666666667),
 ('Electrical Engineers', 62918.98717948718),
 ('College, university and higher education teaching professionals',
  61286.427083333336),
 ('Production and operations managers in manufacturing', 60356.818181818184),
 ('Economists', 60168.75),
 ('Authors, journalists and other writers', 59714.04166666667),
 ('Supply and distribution managers', 59390.944444444445),
 ('Personnel and human resource development professionals', 58664.12500000001),
 ('Estate agents', 58510.28333333333),
 ('Science and mathematics teaching professionals', 58173.7380952381),
 ('Sales supervisors in wholesale trade', 58047.370370370365),
 ('Other supervisors, n. e. c.', 56821.84833333333),
 ('Nonformal education teaching professionals other than technical and vocational trainors/instructors',
  56695.5),
 ('Government tax and excise officials', 55590.944444444445),
 ('Accountants and auditors', 55567.08552631579),
 ('Foresters and related scientists', 55154.851851851854),
 ('Other administrative associate professionals', 54874.29824561403),
 ('Statisticians', 54798.85),
 ('Mining and metallurgical engineering technicians', 54566.33333333333),
 ('Science and mathematics elementary education teaching professionals',
  54361.833333333336),
 ('Sales and marketing managers', 54081.9103773585),
 ('Buyers', 53399.73611111112),
 ('General managers/managing proprietors in construction', 52049.54232804233),
 ('Legislative officials', 51812.6265060241),
 ('Technical and commercial sales representatives', 51328.180555555555),
 ('Other computer professionals', 50108.416666666664),
 ('Companions and valets', 49609.083333333336),
 ('Computer programmers', 49340.78571428572),
 ('Appraisers and valuers', 48694.35416666667),
 ('Production and operations managers in wholesale and retail trade',
  48538.694444444445),
 ('Chemists', 47521.083333333336),
 ('Insurance representatives', 47491.4880952381),
 ('Aircraft engine mechanics and fitters', 47482.83333333333),
 ('Vocational education teaching professionals', 47267.430555555555),
 ('Firefighters', 46775.67857142857),
 ('Police officers', 46580.15057471265),
 ('Pharmaceutical assistants', 46369.666666666664),
 ('Geodetic engineers and related professionals', 46042.083333333336),
 ('Education methods specialists', 45487.98333333333),
 ('Mining-plant operators', 45356.95833333333),
 ('Administrative secretaries and related associate professionals',
  45269.52243589743),
 ("Ships' deck officers and pilots", 45053.9375),
 ('Electronics and communications engineers', 45000.805555555555),
 ('Other business professionals', 44811.59444444445),
 ('General secondary education teaching professionals', 44760.045045045044),
 ('Building and fire inspectors', 44368.316666666666),
 ('Other health professionals (except nursing)', 44103.72222222222),
 ('Sales supervisors in retail trade', 43794.88782051282),
 ('General elementary education teaching professionals', 43619.6321969697),
 ('Social work professionals', 43556.45),
 ('Metal-wheel grinders, polishers and tool sharpeners', 43381.666666666664),
 ('Librarians, archivists and curators', 43167.416666666664),
 ('Electronics and communications engineering technicians',
  42915.066666666666),
 ('Transport and communications service supervisors n. e. c.',
  42627.59722222222),
 ('Upholsterers and related workers', 42102.916666666664),
 ('Professional midwives', 42089.37500000001),
 ('Mail carriers and sorting clerks', 41713.79761904762),
 ('Other finance and sales associate professionals', 41692.08333333333),
 ('Medical technologists', 41283.645833333336),
 ('Bookkeepers', 40819.34210526317),
 ('Optometrists and opticians', 40705.833333333336),
 ('Professional nurses', 40414.68382352942),
 ('Advertising and public relations managers', 40225.0),
 ('Customs and immigration inspectors', 40003.25),
 ('Postal service supervisors', 39658.5),
 ('Technical and vocational instructors/trainors', 39391.72916666667),
 ('Air traffic safety technicians', 39308.729166666664),
 ('Personal care and related workers, n. e. c.', 39271.416666666664),
 ('Incinerator, water treatment and related plant operators',
  39233.142857142855),
 ('Statistical, mathematical and related associate professionals',
  38582.78787878788),
 ('Veterinary assistants', 38447.166666666664),
 ('Travel consultants and organizers', 38003.61111111112),
 ('Tellers and other counter clerks', 37537.9375),
 ('Decorators and commercial designers', 37444.681818181816),
 ('Other sales supervisors', 36936.875),
 ('Secretaries', 36785.081730769234),
 ('Word processor and related operators', 36235.472222222226),
 ('Technician, skilled, semi-skilled workers', 36041.666666666664),
 ('Medical equipment operators', 35914.46666666667),
 ('General managers/managing proprietors of business services',
  35702.364972337484),
 ('Veterinarians', 35697.916666666664),
 ('Other creative or performing artists', 35446.041666666664),
 ('Shoemaking and related machine operators', 35340.0),
 ('Travel guides', 34790.1875),
 ('Staff officers', 34690.65740740741),
 ('Draftsmen', 34528.118055555555),
 ('Receptionists and information clerks', 34215.671195652176),
 ('General managers/managing proprietors of restaurants and hotels',
  34109.20144356956),
 ('Other life science technicians', 34077.771929824565),
 ('Other office clerks', 34008.68241869919),
 ('Combat soldiers', 33888.119047619046),
 ('Ship and aircraft controllers and technicians', 33664.52083333333),
 ('Machine tool operators', 33653.61111111112),
 ('Metal melters, caster and rolling mill operators', 33636.02777777778),
 ('Cement and other mineral products machine operators', 33559.916666666664),
 ('Government licensing officials', 32964.36111111111),
 ('Composers, musicians and singers', 32928.993055555555),
 ('Midwifery associate professionals', 32913.979166666664),
 ('Production supervisors and general foremen', 32783.067850637526),
 ('Other animal raisers', 32719.416666666664),
 ('Accounting and bookkeeping clerks', 32608.615384615383),
 ('Trade brokers', 32333.854166666664),
 ('Telephone switchboard operators', 32302.5),
 ('Coding, proof-reading and related clerks', 31848.166666666668),
 ('Chemical processing plant operators n. e. c.', 31830.833333333332),
 ('Petroleum and natural gas refining plant operators', 31771.75),
 ('Legal and related business associate professionals', 31720.77777777778),
 ('Photographers and image and sound recording equipment operators',
  31684.395833333336),
 ('Other teaching professionals', 31638.11111111111),
 ('Electronics fitters', 31469.30555555556),
 ('Religious professionals', 30762.724137931036),
 ('Glass, ceramics and related plant operators n. e. c.', 30408.666666666668),
 ('Mechanical engineering technicians', 30328.190972222223),
 ('Radio, television and other announcers', 30163.56944444444),
 ('Other engineers and related professionals', 30134.333333333332),
 ('Cashiers and ticket clerks', 30099.674129353236),
 ('Teaching associate professionals', 29976.535714285717),
 ('Stocks clerks', 29766.746710526317),
 ('Paper pulp plant operators', 29363.5),
 ('General managers/managing proprietors in wholesale and retail trade',
  29254.13005424063),
 ('Statistical and finance clerks', 29231.8125),
 ('Pressman letterpresses and related workers', 29044.69444444445),
 ('Lineman, line installers and cable splicers', 28597.363821138213),
 ('Computer equipment operators', 28402.365079365078),
 ('Other government associate professionals', 28209.869047619046),
 ('Labor contractors and employment agents', 28071.25),
 ('Electrical equipment assemblers', 27931.712962962964),
 ('Production and operations managers in personal care, cleaning and relative services',
  27722.833333333336),
 ('Tobacco preparers and tobacco products makers', 27679.666666666668),
 ('Traditional chiefs and heads of villages', 27418.22337164751),
 ('Mechanical machinery assemblers', 27385.03472222222),
 ('Pharmaceutical and toiletry products machine operators', 27287.0),
 ('Safety, health and quality inspectors (vehicles, processes and products)',
  27265.27430555555),
 ('Precision instrument makers and repairers', 27235.083333333332),
 ('Pharmacists', 26816.75),
 ('Athletes and related workers', 26543.429487179485),
 ('Pawnbrokers and money lenders', 26490.409090909092),
 ('Agricultural or industrial machinery mechanics and fitters',
  26298.537037037036),
 ('Riggers and cable splicers', 25640.833333333332),
 ('Nursing associate professionals', 25608.666666666668),
 ('Mineral ore and stone-processing plant operators', 25555.833333333332),
 ('Baked goods and cereal and chocolate products machine operators',
  25513.520833333336),
 ('General managers/managing proprietors in agriculture, hunting, forestry and fishing',
  25175.412304452468),
 ('Library and filing clerks', 25157.869791666668),
 ('Social work associate professionals', 24928.958333333336),
 ('Telecommunication equipment installers and repairers', 24708.6),
 ('Tree nut farmers', 24693.208333333332),
 ('Debt collectors and related workers', 24656.005208333336),
 ('Data entry operators', 24651.674603174608),
 ('Building frame and related trades workers n. e. c.', 24431.933333333334),
 ('Compositors, typesetters and related workers', 24419.166666666668),
 ('Cooks', 24081.969444444443),
 ('Building and related electricians', 24052.678508771936),
 ('Production and operations managers in agriculture, hunting, forestry and fishery',
  24027.25),
 ('Medical assistants', 24024.5625),
 ('Sheet-metal workers', 23995.005555555555),
 ('Car, taxi and van drivers', 23974.819781553397),
 ('Earth-moving and related plant operators', 23857.77419354839),
 ('Other poultry farmers', 23823.42424242424),
 ('Unemployed', 23804.21677061217),
 ('Computer assistants', 23686.833333333336),
 ('General managers/managing proprietors n. e. c.', 23631.489010989008),
 ('Weaving and knitting machine operators', 23313.458333333332),
 ('Metal drawers and extruders', 23309.416666666668),
 ('Tanners', 23268.666666666668),
 ('Fish-farm cultivators (excluding prawns)', 23229.625),
 ('General managers/managing proprietors in manufacturing',
  23209.545763760045),
 ('Pre-elementary education teaching professionals', 23148.06666666667),
 ('Plumbers, pipe fitters and other related workers', 23121.967261904763),
 ('Crane, hoist and related plant operators', 23116.157407407405),
 ('Other physical science and engineering technicians', 22999.833333333332),
 ('Hunters and trappers', 22685.416666666668),
 ('Senior officials of humanitarian and other special-interest organizations',
  22587.36111111111),
 ('Metal finishing, plating and coating machine operators', 22527.25),
 ('Bus drivers', 22401.769696969695),
 ('Market and sidewalk stall vendors', 22237.183304398146),
 ('Sculptors, painters and related artists', 22070.3),
 ('Shoemakers and related workers', 21750.611111111113),
 ('Electrical mechanics and fitters', 21746.75),
 ('General managers/managing proprietors in personal care, cleaning and relative services',
  21494.55401234568),
 ('Street, nightclub and related musicians, singers and dancers', 21427.78125),
 ('Lifting truck operators', 21383.5),
 ('Other machine operators and assemblers', 21362.33333333334),
 ('Dairy products makers', 21326.25),
 ('Transport clerks', 21275.32),
 ('Broadcasting and telecommunications equipment operators',
  21143.555555555555),
 ('Motor vehicle mechanics and related trades workers', 21140.916152263373),
 ('Sugar production machine operators', 21133.770833333332),
 ('Electronic equipment assemblers', 21050.250000000004),
 ('Silk-screen, block and textile printers', 20999.13333333333),
 ('Shop salespersons and demonstrators', 20938.305373704312),
 ('Well drillers and borers and related workers', 20917.30555555555),
 ('Protective services workers n. e. c.', 20842.164192708333),
 ('Choreographers and dancers', 20761.44444444444),
 ('Papermaking plant operators', 20590.0),
 ('Hog raising farmers', 20513.86090909091),
 ('Life science technicians', 20500.0),
 ('General managers/managing proprietors in transportation, storage and communications',
  20362.07949447895),
 ('Waiters, waitresses and bartenders', 20064.089430894313),
 ('Sewers, Embroiderers and related workers', 20000.75747863248),
 ('Ornamental plant growers', 19841.691666666662),
 ('Brewers and wine and other beverage machine operators', 19830.483333333334),
 ('Other personal services workers, n. e. c.', 19824.75),
 ('Non-ordained religious associate professionals', 19800.270370370374),
 ('Chicken farmers', 19704.035984848484),
 ('Chemical products machine operators n. e. c.', 19660.80555555556),
 ('Service and related workers', 19633.645833333336),
 ('Heavy truck and lorry drivers', 19598.53527131783),
 ('Assembling laborers', 19527.225),
 ('Civil engineering technicians', 19480.875),
 ('Grain and spice milling machine operators', 19439.302083333332),
 ('Welders and flamecutters', 19192.140190972223),
 ('Structural-metal preparers, erectors and related workers',
  19102.568965517243),
 ('Undertakers and embalmers', 19081.10784313726),
 ('Door-to-door and telephone salespersons', 19040.093434343435),
 ('Messengers, package and luggage porters and deliverers', 19039.30641821946),
 ('Electrical engineering technicians', 18935.520833333336),
 ('Housekeepers and related workers', 18894.55555555556),
 ('Tool-makers and related workers', 18761.666666666664),
 ('Painters and related workers', 18727.779143897995),
 ('Rubber products machine operators', 18417.817708333332),
 ('Helpers and cleaners in offices, hotels and other establishments',
  18138.831769436998),
 ('Building caretakers', 18117.978174603173),
 ('Institution-based personal care workers', 18060.63285024155),
 ('Stall and market salespersons', 18052.25101626016),
 ('Street ambulant vendors', 18003.121673003803),
 ('Other field crop farmers', 17830.44590643275),
 ('Dairy products machine operators', 17802.333333333332),
 ('Glass makers, cutters, grinders and finishers', 17722.25925925926),
 ('Doorkeepers, watchpersons and related workers', 17683.047413793105),
 ('Miners and quarry workers', 17573.533730158728),
 ('Dental assistants', 17408.083333333332),
 ('Metal, rubber and plastic products assemblers', 17288.791666666668),
 ('Handicraft workers in wood and related materials', 17278.571428571428),
 ('Bleaching, dyeing and cleaning machine operators', 17173.027777777777),
 ("Ship's deck crews and related workers", 17160.350000000002),
 ('Electronics mechanics and servicers', 17133.310185185182),
 ('Production clerks', 17052.704545454544),
 ('Sugarcane farmers', 17044.40570175439),
 ('Shotfirers and blasters', 16966.75),
 ('Plastic products machine operators', 16894.178571428572),
 ('Duck raisers', 16855.196969696968),
 ('Masons and related concrete finishers', 16784.794665012407),
 ('Blacksmiths, hammersmiths, and forging-press workers', 16639.38888888889),
 ('Textile, leather and related patternmakers and cutters',
  16626.297619047622),
 ('Roofers', 16569.809523809523),
 ('Metal molders and coremakers', 16563.416666666668),
 ('Hairdressers, barbers, beauticians and related workers',
  16511.128787878784),
 ('Automated assembly-line operators', 16400.055555555555),
 ('Enlisted personnel n. e. c.', 16326.979166666668),
 ('Home-based personal care workers', 16214.589285714288),
 ('Locomotive engine drivers', 16040.666666666666),
 ('Hand packers and other manufacturing laborers', 15989.014318442152),
 ('Rice farmers', 15949.914472914472),
 ('Weavers, knitters and related workers', 15924.026315789473),
 ('Butchers, fishmongers and related food preparers', 15861.86057692308),
 ('Cabinet/furniture makers and related workers', 15829.641975308641),
 ('Motorcycle drivers', 15787.988407258064),
 ('Bet bookmakers and croupiers', 15750.17132867133),
 ('Sewing machine operators', 15725.166666666668),
 ('Jewelry and precious metal workers', 15724.222222222224),
 ('Food and beverage tasters and graders', 15665.88888888889),
 ('Business machines mechanics and repairers', 15563.333333333334),
 ('Meat and fish processing machine operators', 15554.541666666668),
 ('Floor layers and tile setters', 15465.041666666666),
 ('Wood and related products assemblers', 15386.8),
 ('Sweepers and related laborers', 15371.517543859649),
 ('Carpenters and joiners', 15315.592583333331),
 ('Freight handlers', 15225.342933947773),
 ('Varnishers and related painters', 15196.604938271603),
 ('Child care workers', 15194.617724867727),
 ('Photographic products machine operators', 15153.125),
 ('Tailors, dressmakers and hatters', 15115.605805243444),
 ('Transport conductors', 15106.785714285714),
 ('Machine-tool setters and setter operators', 15035.916666666666),
 ('Food preservers', 14913.783333333331),
 ('Fruit, vegetable and nut processing machine operators', 14721.3),
 ('Paperboard, textile and related products assemblers', 14713.333333333334),
 ('Forest tree planters', 14550.041666666668),
 ('Bakers, pastry cooks and confectionery makers', 14384.766431924883),
 ('Vegetable farmers', 14157.882771164022),
 ('Bookbinders and related workers', 14105.458333333332),
 ('Building construction laborers', 14089.703731097963),
 ('Musical instrument makers and tuners', 14085.833333333334),
 ('Construction and maintenance laborers: roads, dams and similar constructions',
  13770.897849462368),
 ('Other aqua products cultivators', 13728.18333333333),
 ('Marine craft mechanics', 13711.9375),
 ('Fiber preparing, spinning and winding machine operators',
  13663.361111111111),
 ('Farm technicians', 13581.666666666666),
 ('Stone splitters, cutters and carvers', 13539.523809523807),
 ('Garbage collectors', 13454.657051282053),

In [7]:
data_high_income =pd.DataFrame()
for i in a:
    data_high_income = data_high_income.append(data[data['HouseholdHeadOccupation'] == i],  ignore_index=True)

In [8]:
data_high_income.shape

(2364, 61)

In [9]:
obj_df = data_high_income.select_dtypes(include=['object']).copy()
for item in obj_df.columns:
    obj_df[item] = obj_df[item].astype('category')
    obj_df[item] = obj_df[item].cat.codes
obj_df.head()

,Region,MainSourceofIncome,HouseholdHeadSex,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TypeofBuildingHouse,TypeofRoof,TypeofWalls,TenureStatus,ToiletFacilities,MainSourceofWaterSupply
0,9,2,1,2,7,0,7,3,0,4,6,3,4,7,3
1,10,1,1,3,20,0,56,2,1,4,6,3,4,7,3
2,10,2,0,2,33,0,56,2,0,1,6,3,4,7,3
3,12,1,1,2,20,0,56,0,0,4,6,3,4,7,3
4,15,1,0,2,20,0,56,2,0,4,6,3,4,7,3

In [10]:
data2 = data_high_income.copy()
for item in data2.columns:
    if item in obj_df.columns:
        data2[item] = obj_df[item]
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,NumberofTelevision,NumberofCDVCDDVD,NumberofComponentStereoset,NumberofRefrigeratorFreezer,NumberofWashingMachine,NumberofAirconditioner,NumberofCarJeepVan,NumberofLandlinewirelesstelephones,NumberofCellularphone,NumberofPersonalComputer,NumberofStovewithOvenGasRange,NumberofMotorizedBanca,NumberofMotorcycleTricycle,TotalHouseholdIncome_monthly
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,1,1,1,1,1,3,3,1,5,2,1,0,0,174160.916667
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,2,1,1,1,0,1,0,0,1,0,1,0,0,33624.500000
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,2,3,0,1,1,2,1,0,3,1,1,0,0,67862.500000
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,2,1,0,1,1,2,3,1,5,3,1,0,0,34600.000000
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,2,1,1,1,0,2,1,1,7,3,1,0,0,167415.000000

In [11]:
data2['TotalMovableAssests'] = data2['NumberofTelevision'] + data2['NumberofCDVCDDVD'] + data2['NumberofComponentStereoset'] + data2['NumberofRefrigeratorFreezer'] + data2['NumberofWashingMachine'] + data2['NumberofAirconditioner'] + data2['NumberofCarJeepVan'] + data2['NumberofLandlinewirelesstelephones'] + data2['NumberofCellularphone'] + data2['NumberofPersonalComputer'] + data2['NumberofStovewithOvenGasRange'] + data2['NumberofMotorizedBanca'] + data2['NumberofMotorcycleTricycle']

In [12]:
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,NumberofTelevision,NumberofCDVCDDVD,NumberofComponentStereoset,NumberofRefrigeratorFreezer,NumberofWashingMachine,NumberofAirconditioner,NumberofCarJeepVan,NumberofLandlinewirelesstelephones,NumberofCellularphone,NumberofPersonalComputer,NumberofStovewithOvenGasRange,NumberofMotorizedBanca,NumberofMotorcycleTricycle,TotalHouseholdIncome_monthly,TotalMovableAssests
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,1,1,1,1,1,3,3,1,5,2,1,0,0,174160.916667,20
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,2,1,1,1,0,1,0,0,1,0,1,0,0,33624.500000,8
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,2,3,0,1,1,2,1,0,3,1,1,0,0,67862.500000,15
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,2,1,0,1,1,2,3,1,5,3,1,0,0,34600.000000,20
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,2,1,1,1,0,2,1,1,7,3,1,0,0,167415.000000,20

In [13]:
data2 = data2.drop(['NumberofTelevision', 'NumberofCDVCDDVD', 'NumberofComponentStereoset', 'NumberofRefrigeratorFreezer', 'NumberofWashingMachine', 'NumberofAirconditioner', 'NumberofCarJeepVan', 'NumberofLandlinewirelesstelephones', 'NumberofCellularphone', 'NumberofPersonalComputer', 'NumberofStovewithOvenGasRange', 'NumberofMotorizedBanca', 'NumberofMotorcycleTricycle'], axis = 1)

In [14]:
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,TotalHouseholdIncome_monthly,TotalMovableAssests
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,174160.916667,20
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,33624.500000,8
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,67862.500000,15
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,34600.000000,20
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,167415.000000,20

In [15]:
data2.shape

(2364, 49)

## ========================================================================

# Savings

In [16]:
expenditures = [column for column in data2.columns if 'Expenditure' in column]

In [17]:
expenditures

['TotalFoodExpenditure',
 'BreadandCerealsExpenditure',
 'TotalRiceExpenditure',
 'MeatExpenditure',
 'TotalFishandmarineproductsExpenditure',
 'FruitExpenditure',
 'VegetablesExpenditure',
 'RestaurantandhotelsExpenditure',
 'AlcoholicBeveragesExpenditure',
 'TobaccoExpenditure',
 'ClothingFootwearandOtherWearExpenditure',
 'HousingandwaterExpenditure',
 'MedicalCareExpenditure',
 'TransportationExpenditure',
 'CommunicationExpenditure',
 'EducationExpenditure',
 'MiscellaneousGoodsandServicesExpenditure',
 'SpecialOccasionsExpenditure']

In [18]:
data2['TotalOverallExpenditure'] = data2['BreadandCerealsExpenditure'] + data2['TotalRiceExpenditure'] + data2['MeatExpenditure'] + data2['TotalFishandmarineproductsExpenditure'] + data2['FruitExpenditure'] + data2['VegetablesExpenditure'] + data2['RestaurantandhotelsExpenditure'] + data2['AlcoholicBeveragesExpenditure'] + data2['TobaccoExpenditure'] + data2['ClothingFootwearandOtherWearExpenditure'] + data2['HousingandwaterExpenditure'] + data2['MedicalCareExpenditure'] + data2['TransportationExpenditure'] + data2['CommunicationExpenditure'] + data2['EducationExpenditure'] + data2['MiscellaneousGoodsandServicesExpenditure'] + data2['SpecialOccasionsExpenditure']

In [19]:
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,TotalHouseholdIncome_monthly,TotalMovableAssests,TotalOverallExpenditure
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,174160.916667,20,1039844
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,33624.500000,8,177167
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,67862.500000,15,585242
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,34600.000000,20,499822
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,167415.000000,20,673535

In [20]:
data2['TotalAnnualSavings'] = data2['TotalHouseholdIncome'] - data2['TotalOverallExpenditure']

In [21]:
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,TotalHouseholdIncome_monthly,TotalMovableAssests,TotalOverallExpenditure,TotalAnnualSavings
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,174160.916667,20,1039844,1050087
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,33624.500000,8,177167,226327
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,67862.500000,15,585242,229108
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,34600.000000,20,499822,-84622
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,167415.000000,20,673535,1335445

In [22]:
data2['SavingRate'] = data2['TotalAnnualSavings']/data2['TotalHouseholdIncome'] * 100

In [24]:
data2.head()

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadHighestGradeCompleted,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,TotalHouseholdIncome_monthly,TotalMovableAssests,TotalOverallExpenditure,TotalAnnualSavings,SavingRate
0,2089931,9,390989,2,2,58956,36787,36136,37342,6550,7260,189300,3272,600,17175,363240,180000,5226,98070,57588,0,115842,6500,0,0,1,66,2,7,0,7,3,0,7,1,0,5,4,6,3,150,25,7,4,7,1,3,174160.916667,20,1039844,1050087,50.245056
1,403494,10,43377,1,0,11964,9560,6276,6348,7130,1899,780,680,0,5680,73056,48000,14080,20766,4200,0,14748,0,0,92200,1,54,3,20,0,56,2,1,1,0,0,1,4,6,3,96,50,3,4,7,1,3,33624.500000,8,177167,226327,56.091788
2,814350,10,151800,2,0,39114,23738,22324,12447,9591,10722,31380,0,0,14459,148764,69000,54570,53676,17244,34200,60468,52545,0,23000,0,53,2,33,0,56,2,0,4,0,1,2,1,6,3,60,13,4,4,7,1,3,67862.500000,15,585242,229108,28.133849
3,415200,12,151756,1,0,31023,18900,28239,14410,5230,5390,34200,0,0,4450,190242,150000,66260,37284,23400,23000,10824,6970,0,149000,1,76,2,20,0,56,0,0,5,0,0,1,4,6,3,100,45,5,4,7,1,3,34600.000000,20,499822,-84622,-20.381021
4,2008980,15,202613,1,0,46374,28565,34305,17402,13782,10393,32242,1890,0,29608,161076,120000,12140,98346,16512,71640,81660,17600,355980,355980,0,39,2,20,0,56,2,0,6,0,2,2,4,6,3,80,15,3,4,7,1,3,167415.000000,20,673535,1335445,66.473783

In [25]:
byedu = data2.groupby(by='HouseholdHeadHighestGradeCompleted', as_index=True).mean().sort_values(by='SavingRate', ascending=False)

In [26]:
byedu

,TotalHouseholdIncome,Region,TotalFoodExpenditure,MainSourceofIncome,AgriculturalHouseholdindicator,BreadandCerealsExpenditure,TotalRiceExpenditure,MeatExpenditure,TotalFishandmarineproductsExpenditure,FruitExpenditure,VegetablesExpenditure,RestaurantandhotelsExpenditure,AlcoholicBeveragesExpenditure,TobaccoExpenditure,ClothingFootwearandOtherWearExpenditure,HousingandwaterExpenditure,ImputedHouseRentalValue,MedicalCareExpenditure,TransportationExpenditure,CommunicationExpenditure,EducationExpenditure,MiscellaneousGoodsandServicesExpenditure,SpecialOccasionsExpenditure,CropFarmingandGardeningexpenses,TotalIncomefromEntrepreneurialAcitivites,HouseholdHeadSex,HouseholdHeadAge,HouseholdHeadMaritalStatus,HouseholdHeadJoborBusinessIndicator,HouseholdHeadOccupation,HouseholdHeadClassofWorker,TypeofHousehold,TotalNumberofFamilymembers,Memberswithagelessthan5yearold,Memberswithage517yearsold,Totalnumberoffamilymembersemployed,TypeofBuildingHouse,TypeofRoof,TypeofWalls,HouseFloorArea,HouseAge,Numberofbedrooms,TenureStatus,ToiletFacilities,Electricity,MainSourceofWaterSupply,TotalHouseholdIncome_monthly,TotalMovableAssests,TotalOverallExpenditure,TotalAnnualSavings,SavingRate
HouseholdHeadHighestGradeCompleted,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
38,3.833650e+05,12.500000,73969.500000,2.000000,0.000000,19573.750000,12518.750000,11874.250000,7049.750000,2141.250000,2771.750000,17487.500000,457.500000,130.000000,5927.000000,39780.000000,24750.000000,1807.000000,20950.500000,4380.000000,4735.000000,19830.000000,8500.000000,0.000000,6764.000000,0.000000,33.750000,1.750000,0.0,107.500000,2.250000,0.750000,2.500000,0.250000,0.750000,1.250000,4.000000,5.250000,2.500000,52.500000,27.250000,2.000000,4.000000,7.000000,1.000000,3.250000,31947.083333,5.250000,179914.000000,203451.000000,48.122890
44,8.394233e+05,11.500000,171942.166667,1.000000,0.333333,39008.000000,24173.666667,23197.333333,23845.666667,6485.833333,8817.833333,32625.500000,1583.500000,1553.666667,18359.500000,98488.000000,49000.000000,22043.000000,32969.000000,15535.000000,14555.000000,40999.000000,13177.500000,9846.666667,156779.333333,0.666667,37.166667,2.166667,0.0,83.000000,2.000000,0.666667,3.166667,0.333333,0.333333,1.500000,4.000000,6.000000,3.000000,118.833333,24.666667,2.500000,4.333333,7.000000,1.000000,3.000000,69951.944444,12.833333,417417.000000,422006.333333,44.698244
0,9.882555e+05,7.267857,155937.857143,1.839286,0.250000,30882.875000,20342.642857,22980.839286,23670.500000,5590.053571,7630.160714,35339.071429,2107.535714,2678.071429,19142.267857,77813.142857,42857.142857,37206.500000,36669.428571,13732.285714,16645.821429,56754.857143,18976.250000,29357.321429,142778.642857,0.910714,51.464286,2.160714,0.0,46.000000,2.000000,0.607143,4.428571,0.142857,1.142857,2.035714,3.803571,5.910714,2.875000,91.053571,21.660714,2.892857,4.000000,6.892857,0.946429,3.625000,82354.626488,12.321429,428162.303571,560093.214286,43.311526
27,4.783630e+05,10.000000,101574.666667,1.666667,0.000000,28855.333333,9155.333333,5559.666667,3862.666667,1223.333333,2345.333333,46727.000000,333.333333,0.000000,40355.000000,46744.000000,30000.000000,11633.666667,28424.000000,7260.000000,4566.666667,33642.000000,5333.333333,16118.666667,19268.666667,1.000000,41.666667,2.333333,0.0,93.333333,2.666667,0.666667,3.000000,0.333333,0.333333,2.000000,4.000000,6.000000,3.000000,80.666667,9.666667,3.000000,4.000000,6.666667,1.000000,3.333333,39863.583333,13.333333,276020.666667,202342.333333,41.703761
33,1.004200e+06,8.327381,172723.511905,1.761905,0.214286,32204.404762,19831.261905,25450.863095,19453.833333,7431.488095,8751.654762,45769.142857,1830.952381,1132.047619,23684.339286,141780.250000,91912.500000,30116.011905,56714.607143,21364.857143,43001.226190,66017.857143,22745.202381,10128.773810,106689.613095,0.702381,52.857143,2.315476,0.0,54.458333,2.136905,0.601190,4.720238,0.267857,1.130952,2.017857,3.815476,5.863095,2.946429,121.785714,22.654762,3.244048,4.000000,6.875000,1.000000,3.625000,83683.332837,14.297619,567280.000000,436919.994048,41.064230
13,6.518365e+05,9.083333,142121.250000,1.666667,0.583333,24834.416667,15802.083333,22338.500000,12608.083333,3952.833333,4599.750000,47175.333333,1263.833333,2986.583333,16993.583333,108974.500000,51300.000000,9291.250000,36982.000000,19850.000000,31060.833333,32150.000000,11958.333333,41348.583333,74270.416667,0.666667,47.250000,2.166667,0.0,66.750000,2.333333,0.750000,3.833333,0.166667,1.000000,1.583333,3.833333,6.000000,2.666667,63.583333,16.666667,2.250000,4.416667,6.833333,1.000000,4.333333,54319.708333,11.833333,402821.916667,249014.583333,38.086337
40,5.374350e+05,8.036620,121981.535211,1.847887,0.239437,28566.664789,19142.735211,17476.639437,14079.138028,4518.960563,6651.194366,25989.611268,829.309859,1226.033803,12444.569014,60836.467606,32608.732394,15502.800000,21433.791549,9956.450704,18947.490141,44674.816901,12316.726761,4922.304225,23248.174648,0.461972,46.329577,2.363380,0.0,45.822535,2.104225,0.678873,4.152113,0.278873,1.185915,1.729577,3.915493,5.819718,2.842254,83.929577,20.236620,2.526761,3.969014,6.800000,0.983099,3.676056,44786.252582,9.735211,314593.400000,222841.630986,38.011753
24,1.444197e+06,8.320000,241756.840000,1.640000,0.640000,35080.880000,21393.120000,31759.760000,18942.640000,9764.920000,10986.800000,95336.560000,1606.960000,1833.440000,30436.280000,289377.600000,194640.000000,26673.560000,86441.280000,40032.960000,54956.000000,63636.240000,23020.000000,0.000000,193550.640000,0.880000,56.880000,2.280000,0.0,53.600000,2.240000,0.760000,4.680000,0.160000,0.640000,2.480000,3.760000,6.000000,2.920000,181.080000,29.240000,3.400000,4.040000,7.000000,1.000000,2.960000,120349.776667,19.160000,841279.000000,602918.320000,36.957260
25,9.416202e+05,8.666667,210356.666667,1.666667,0.666667,39405.666667,25348.666667,29248.833333,19867.000000,5358.333333,7330.500000,69248.333333,2948.666667,3333.500000,32335.666667,126286.000000,73200.000000,25271.833333,52458.000000,17694.000000,38703.333333,73446.000000,23833.333333,0.000000,46645.833333,0.833333,42.666667,2.000000,0.0,34.000000,2.666667,0.500000,5.833333,0.500000,2.000000,2.333333,4.000000,6.000000,3.000000,120.833333,26.333333,2.833333,3.166667,7.000000,1.000000,3.666667,78468.347222,14.500000,592117.666667,349502.500000,36.193582
22,4.721410e+05,8.714286,113037.285714,1.642857,0.214286,24346.071429,15793.000000,16733.642857,12478.071429,3371.928571,5580.357143,27416.071429,742.642857,900.500000,7553.928571,78284.142857,41978.571429,7064.071429,26700.428571,7709.142857,16956.428571,23903.571429,10834.285714,18240.785714,40885.500000,0.642857,53.000000,2.428571,0.0,47.285714,2.000000,0.642857,4.214286,0.214286,0.928571,1.642857,3.571429,6.000000,3.000000,80.214286,20.714286,2.642857,4.142857,7.000000,0.928571,4.642857,39345.083333,8.571429,286368.285714,185772.714286,35.030704
19,1.794500e+05,4.000000,55882.000000,0.000000,1.000000,24072.000000,21376.000000,5555.000000,5558.000000,2990.000000,9605.000000,0.000000,480.000000,7013.000000,5164.000000,13170.000000,3600.000000,630.000000,10638.000000,1080.000000,1700.000000,8358.000000,0.000000,91090.000000,91090.000000,1.000000,51.000000,2.000000,0.0,51.000000,2.000000,1.000000,7.000000,0.000000,4.000000,1.000000,4.000000,6.000000,3.000000,30.000000,13.000000,2.000000,4.000000,0.000000,1.000000,6.000000,14954.166667,6.000000,117389.000000,62061.000000,34.584007
3,5.477115e+05,6.400000,128144.400000,1.900000,0.200000,29683.100000,21841.200000,16902.900000,18483.200000,3302.500000,5981.300000,29459.200000,745.000000,3631.400000,11852.100000,57200.400000,24420.000000,6999.000000,59496.600000,9574.800000,25254.500000,41742.600000,12240.600000,2716.400000,38955.000000,0.900000,48.800000,2.000000,0.0,61.900000,2.100000,0.600000,5.100000,0.300000,1.100000,1.400000,4.000000,6.000000,3.000000,69.100000,18.400000,2.200000,3.900000,7.000000,1.000000,3.900000,45642.625000,11.200000,354390.400000,193321.100000,33.394636
37,6.235769e+05,7.848485,148250.767677,1.878788,0.404040,31641.989899,21518.515152,23438.707071,16223.181818,5162.404040,7621.393939,35474.717172,1716.858586,2857.666667,15358.949495,83386.909091,42766.666667,16115.919192,37604.545455,13661.636364,27736.010101,44542.000000,14997.737374,8330.212121,49820.787879,1.000000,44.010101,2.040404,0.0,80.191919,2.050505,0.696970,4.959596,0.404040,1.575758,1.767677,3.757576,5.666667,2.878788,74.434343,19.707071,2.404040,3.959596,6.828283,0.969697,3.191919,51964.739899,11.434343,399059.141414,224517.737374,32.997098
29,6.828828e+05,9.500000,156600.666667,1.000000,0.000000,29699.500000,19247.833333,27623.833333,21425.500000,4987.500000,9982.166667,31909.500000,984.333333,505.000000,10812.666667,87129.000000,47500.000000,22538.833333,33064.000000,12790.000000,75313.666667,29716.000000,29550.000000,0.000000,180600.000000,1.000000,50.000000,2.333333,0.0,54.833333,2.000000,0.833333,4.333333,0.166667,1.666667,1.166667,4.000000,6.000000,3.000000,99.000000,26.166667,3.833333,4.000000,7.000000,1.000000,2.666667,56906.902778,11.666667,447279.333333,235603.500000,32.433565
31,6.723957e+05,8.368421,162756.210526,1.526316,0.631579,30640.736842,18462.842105,25078.421053,16445.052632,4996.894737,7694.947368,52690.842105,1167.105263,2593.578947,20127.631579,106309.263158,49736.842105,17055.894737,41732.210526,19470.000000,33354.210526,39483.157895,13333.157895,0.000000,82372.315789,0.526316,43.736842,2.315789,0.0,57.315789,1.947368,0.789474,4.210526,0.263158,1.263158,1.578947,3.894737,6.000000,3.000000,83.947368,27.631579,2.684211,3.789474,7.000000,1.000000,3.052632,56032.978070,11.894737,450635.947368,221759.789474,32.050147
7,7.871257e+05,8.194656,164767.522901,1.751908,0.480916,29727.793893,19212.076336,24378.385496,16723.095420,6160.610687,7425.858779,52118.053435,1647.442748,1633.698473,16670.847328,119180.725191,66127.099237,21117.912214,44191.145038,20107.969466,37757.106870,46002.206107,13650.156489,5368.007634,84409.305344,0.950382,48.496183,2.099237,0.0,45.729008,2.343511,0.732824,4.545802,0.240458,0.984733,1.931298,3.824427,5.900763,2.912214,99.488550,22.118321,2.812977,4.072519,6.908397,1.000000,3.374046,65593.806298,13.057252,477705.083969,309420.591603,31.832473
26,5.286935e+05,8.500000,183188.000000,2.000000,1.000000,19592.500000,14391.000000,43948.500000,35797.000000,7629.000000,4881.500000,45290.000000,210.000000,78.000000,4166.500000,110967.000000,73500.000000,914.500000,40026.000000,9960.000000,15505.000000,29223.000000,6000.000000,0.000000,157233.500000,1.000000,45.000000,2.000000,0.0,41.000000,1.500000,1.000000,4.000000,0.500000,1.500000,1.000000,4.000000,6.000000,3.000000,130.000000,27.500000,2.500000,5.000000,7.000000,1.000000,3.000000,44057.791667,9.000000,388579.500000,140114.000000,31.698258
28,1.786220e+05,6.666667,47999.666667,0.333333,0.666667,11366.666667,8476.666667,5641.666667,4095.666667,2682.333333,2023.666667,12283.333333,65.000000,603.333333,1285.000000,62052.000000,51200.000000,3940.000000,1908.000000,874.000000,320.000000,4782.000000,2016.666667,0.000000,71090.666667,0.000000,77.000000,3.666667,0.0,39.000000,1.000000,0.666667,2.333333,0.000000,0.333333,0.000000,4.000000,4.333333,3.333333,58.333333,13.333333,1.666667,4.000000,6.666667,1.000000,4.333333,14885.166667,4.333333,124416.000000,54206.000000,31.656831
43,7.225897e+05,10.076923,165976.846154,1.384615,0.307692,35205.615385,23969.423077,25701.346154,20084.538462,6676.538462,7888.692308,32030.692308,1112.692308,2318.500000,16391.192308,93285.923077,49846.153846,26096.384615,67268.769231,18409.153846,13728.000000,41338.615385,14711.307692,1638.269231,170955.538462,0.961538,50.500000,2.038462,0.0,57.038462,2.346154,0.615385,4.846154,0.423077,1.038462,1.961538,3.769231,6.000000,2.846154,98.000000,20.884615,2.653846,3.923077,6.884615,1.000000,3.153846,60215.804487,13.538462,446217.384615,276372.269231,31.557135
4,6.573922e+05,8.276276,147706.105105,1.675676,0.543544,27977.282282,17564.042042,20968.321321,14237.492492,5087.984985,6762.186186,43321.654655,1104.774775,1358.960961,13930.528529,120798.684685,71073.423423,16703.654655,35646.900901,16783.711712,33073.687688,38215.603604,12493.576577,1828.441441,63425.099099,0.639640,48.822823,2.267267,0.0,57.567568,2.366366,0.699700,4.210210,0.234234,1.078078,1.657658,3.705706,5.900901,2.957958,91.477477,24.093093,2.609610,4.120120,6.876877,0.996997,3.351351,54782.686937,11.453453,426029.048048,231363.195195,30.267534
20,8.012883e+05,8.683761,157531.769231,1.470085,0.495726,26228.880342,16156.495726,22395.017094,15337.350427,6462.675214,7636.290598,46742.957265,1451.717949,1723.829060,16877.384615,145538.974359,78210.256410,15850.854701,49920.769231,20528.512821,37517.564103,48554.769231,20096.863248,7768.948718,180380.752137,0.555556,44.803419,2.196581,0.0,66.376068,2.094017,0.709402,4.051282,0.299145,0.837607,1.649573,3.777778,5.905983,2.957265,108.367521,25.401709,2.803419,4.196581,6.914530,1.000000,3.264957,66774.027066,13.273504,499020.905983,302267.418803,30.093805
39,8.172815e+05,8.431818,173932.181818,1.840909,0.454545,30830.704545,19825.545455,23048.136364,15690.863636,6752.363636,7157.295455,57796.272727,1969.295455,2176.590909,17451.863636,113834.590909,64009.090909,17628.431818,62044.636364,18601.772727,37135.500000,50527.363636,14949.863636,546.590909,49155.181818,0.795455,47.477273,2.113636,0.0,66.068182,2.181818,0.704545,4.454545,0.204545,1.045455,1.909091,3.704545,5.818182,2.909091,86.068182,22.795455,2.863636,3.954545,6.909091,1.000000,3.318182,68106.787879,12.340909,497421.090909,319860.363636,28.358292
30,4.541323e+05,11.666667,140103.333333,2.000000,0.666667,31469.666667,22986.000000,12605.000000,14937.333333,5290.333333,5138.000000,43506.666667,1977.666667,1213.333333,9414.000000,82910.000000,42000.000000,5979.333333,25718.000000,7774.000000,12083.333333,35416.000000,12233.333333,0.000000,28249.333333,0.666667,56.333333,2.333333,0.0,104.000000,2.000000,0.666667,4.000000,0.333333,0.333333,1.000000,4.000000,6.000000,3.000000,50.666667,27.333333,3.000000,3.666667,7.000000,1.000000,3.000000,37844.361111,9.000000,330652.000000,123480.333333,27.542036
5,5.585629e+05,8.107143,143973.339286,1.732143,0.571429,26795.214286,16300.446429,20649.089286,11315.428571,4292.910714,6372.446429,41911.839286,800.035714,2060.482143,14243.571429,92891.035714,54267.857143,15841.946429,36540.964286,15005.142857,21931.053571,33602.785714,10279.410714,337.857143,39730.017857,0.857143,38.178571,2.089286,0.0,62.946429,2.571429,0.785714,4.196429,0.446429,1.339286,1.500000,3.821429,5.839286,2.875000,91.357143,22.482143,2.375000,4.250000,6.857143,0.982143,3.214286,46546.907738,10.714286,370833.803571,187729.089286,27.376448
34,5.606879e+05,8.100000,139490.150000,1.412500,0.450000,30540.600000,20358.575000,19984.187500,13240.700000,4407.637500,6413.137500,37082.862500,1778.075000,2903.500000,11645.750000,98274.450000,48547.500000,11189.475000,27928.125000,13236.825000,25298.900000,31292.700000,13825.937500,2010.825000,99257.825000,0.862500,50.600000,2.200000,0.0,56.900000,1.887500,0.725000,4.762500,0.225000,1.175000,1.637500,3.862500,5.812500,2.912500,79.800000,23.312500,2.337500,3.950000,6.862500,0.987500,3.400000,46723.990625,10.712500,369401.437500,191286.450000,27.048561
2,8.389183e+05,8.142857,154217.000000,1.142857,1.142857,27402.142857,18273.000000,23283.857143,13987.142857,6768.285714,8299.285714,46645.714286,1822.571429,3645.428571,17905.000000,233732.571429,90428.571429,14413.857143,26964.000000,22852.285714,17448.571429,38277.428571,10207.142857,0.000000,286404.285714,0.857143,53.285714,2.428571,0.0,54.285714,1.571429,0.428571,4.714286,0.285714,0.857143,1.285714,3.857143,5.571429,2.714286,139.714286,32.428571,3.000000,4.000000,7.000000,1.000000,3.000000,69909.857143,13.428571,531928.285714,306990.000000,26.565859
1,7.866670e+05,8.190476,172977.619048,1.761905,0.857143,29733.904762,19188.142857,25061.857143,16123.333333,5633.476190,6656.809524,59528.714286,1748.904762,2531.666667,18182.809524,184018.000000,111514.285714,14384.809524,49438.571429,24106.000000,44760.904762,36327.142857,12345.714286,2635.952381,140510.047619,0.952381,46.285714,2.142857,0.0,39.904762,2.428571,0.714286,4.761905,0.285714,1.285714,2.142857,3.952381,6.000000,3.000000,152.476190,26.952381,3.190476,4.047619,7.000000,1.000000,3.380952,65555.583333,13.952381,549770.761905,236896.238095,25.626538
41,5.786514e+05,8.329114,139734.797468,1.316456,0.658228,27313.278481,18638.253165,18258.582278,13155.531646,5099.126582,6188.556962,45438.481013,1071.354430,2119.202532,14100.126582,103633.518987,54531.645570,14975.683544,26536.708861,14064.759494,16796.607595,29687.544304,12240.544304,4104.493671,140263.518987,0.835443,50.341772,2.215190,0.0,52.265823,1.772152,0.658228,4.632911,0.291139,1.151899,1.392405,3.658228,5.772152,2.797468,71.898734,27.151899,2.101266,4.177215,6.759494,1.000000,3.265823,48220.948312,10.392405,369317.860759,209333.518987,24.130753
23,4.926007e+05,8.428571,149711.142857,1.571429,0.285714,30097.285714,16358.857143,24032.571429,15275.142857,4641.714286,9358.142857,26392.428571,3322.285714,2010.285714,17132.428571,80390.571429,48000.000000,21669.857143,39294.000000,11249.142857,31495.714286,35775.428571,18522.142857,0.000000,37714.285714,0.714286,46.571429,2.142857,0.0,77.142857,2.285714,0.857143,3.857143,0.571429,0.714286,1.428571,4.000000,6.000000,3.000000,77.000000,20.857143,2.857143,4.000000,7.000000,1.000000,3.857143,41050.059524,11.857143,387018.000000,105582.714286,22.843484
9,4.691935e+05,13.000000,119951.750000,2.000000,0.500000,26381.500000,20727.000000,18977.500000,11323.750000,4219.500000,4938.750000,24580.000000,1535.500000,0.000000,11647.250000,67762.500000,34650.000000,11982.000000,34491.000000,12360.000000,9128.750000,27070.500000,9050.000000,0.000000,8000.000000,1.000000,41.750000,2.000000,0.0,70.750000,2.000000,1.000000,5.250000,0.750000,2.000000,2.000000,2.750000,6.000000,3.000000,46.500000,25.500000,1.750000,4.250000,6.250000,1.000000,3.250000,39099.458333,10.750000,296175.500000,173018.000000,21.913353
36,3.189979e+05,5.750000,113159.750000,1.500000,0.666667,23703.000000,16142.333333,14772.583333,10226.250000,4369.833333,3717.416667,36683.750000,1098.333333,2405.666667,9573.000000,50784.500000,22650.000000,5322.666667,16897.000000,7633.500000,14475.416667,16033.000000,6760.833333,0.000000,30096.583333,1.000000,42.666667,2.166667,0.0,59.833333,2.000000,0.916667,4.166667,0.333333,1.333333,1.333333,3.666667,4.666667,2.666667,43.916667,22.666667,1.500000,3.750000,6.583333,0.916667,3.750000,26583.159722,6.833333,240599.083333,78398.833333,21.883489
10,4.329323e+05,7.866667,129392.200000,1.633333,0.400000,27519.866667,18598.466667,20607.633333,14025.933333,4135.366667,5990.966667,32403.900000,2221.966667,4054.433333,7000.400000,71561.800000,43680.000000,10889.866667,27792.800000,8971.400000,17067.233333,28526.200000,13087.333333,265.266667,45761.000000,0.833333,47.566667,2.166667,0.0,64.333333,2.066667,0.700000,4.633333,0.266667,1.300000,1.600000,3.866667,6.000000,2.866667,70.100000,21.033333,2.000000,4.000000,6.666667,1.000000,3.900000,36077.694444,9.066667,314455.566667,118476.766667,21.570316
6,2.546312e+05,9.806452,80629.209677,1.096774,0.177419,24696.177419,18756.645161,11219.387097,10794.096774,2205.370968,4564.322581,12945.887097,1130.032258,2673.387097,3922.258065,40360.935484,22195.161290,10784.790323,11595.483871,4433.129032,8002.225806,11035.548387,6125.532258,2829.919355,70728.177419,0.838710,55.983871,2.387097,0.0,43.354839,1.161290,0.596774,4.822581,0.354839,1.370968,0.967742,3.951613,5.129032,2.112903,50.161290,20.354839,1.887097,3.709677,6.564516,1.000000,4.629032,21219.263441,6.032258,185245.209677,69385.951613,20.842797

In [28]:
data_high_income['HouseholdHeadHighestGradeCompleted'].value_counts()

Teacher Training and Education Sciences Programs                                                                                                                                                                       355
Business and Administration Programs                                                                                                                                                                                   333
Engineering and Engineering Trades Programs                                                                                                                                                                            262
High School Graduate                                                                                                                                                                                                   251
Post Baccalaureate                                                                                                                                                                                                     168
Health Programs                                                                                                                                                                                                        117
Security Services Programs                                                                                                                                                                                              99
Second Year College                                                                                                                                                                                                     80
Third Year College                                                                                                                                                                                                      79
Elementary Graduate                                                                                                                                                                                                     62
Engineering and Engineering trades Programs                                                                                                                                                                             58
Agriculture, Forestry, and Fishery Programs                                                                                                                                                                             56
Computing/Information Technology Programs                                                                                                                                                                               56
Social and Behavioral Science Programs                                                                                                                                                                                  44
First Year College                                                                                                                                                                                                      30
Third Year High School                                                                                                                                                                                                  27
Transport Services Programs                                                                                                                                                                                             26
Second Year High School                                                                                                                                                                                                 26
Law Programs                                                                                                                                                                                                            25
Architecture and Building Programs                                                                                                                                                                                      21
Personal Services Programs                                                                                                                                                                                              19
First Year High School                                                                                                                                                                                                  17
Grade 5                                                                                                                                                                                                                 15
Grade 3                                                                                                                                                                                                                 15
Humanities Programs                                                                                                                                                                                                     14
Second Year Post Secondary                                                                                                                                                                                              12
Fourth Year College                                                                                                                                                                                                     12
Grade 4                                                                                                                                                                                                                 11
Basic Programs                                                                                                                                                                                                          10
Journalism and Information Programs                                                                                                                                                                                      7
Arts Programs                                                                                                                                                                                                            7
Other Programs in Education at the Third Level, First Stage, of the Type that Leads to an Award not Equivalent to a First University or Baccalaureate Degree                                                             6
Life Sciences Programs                                                                                                                                                                                                   6
Veterinary Programs                                                                                                                                                                                                      6
Social Services Programs                                                                                                                                                                                                 4
Grade 2                                                                                                                                                                                                                  4
First Year Post Secondary                                                                                                                                                                                                4
Environmental Protection Programs                                                                                                                                                                                        4
Other Programs of Education at the Third Level, First Stage, of the Type that Leads to a Baccalaureate or First University/Professional Degree (HIgher Education Level, First Stage, or Collegiate Education Level)      3
Grade 1                                                                                                                                                                                                                  3
No Grade Completed                                                                                                                                                                                                       3
Mathematics and Statistics Programs                                                                                                                                                                                      3
Manufacturing and Processing Programs                                                                                                                                                                                    2
Grade 6                                                                                                                                                                                                                  1
Physical Sciences Programs                                                                                                                                                                                               1
Name: HouseholdHeadHighestGradeCompleted, dtype: int64

In [30]:
for i in range(len(data_high_income['HouseholdHeadHighestGradeCompleted'].value_counts())):
    print(i, data_high_income['HouseholdHeadHighestGradeCompleted'].value_counts()[i])

0 355
1 333
2 262
3 251
4 168
5 117
6 99
7 80
8 79
9 62
10 58
11 56
12 56
13 44
14 30
15 27
16 26
17 26
18 25
19 21
20 19
21 17
22 15
23 15
24 14
25 12
26 12
27 11
28 10
29 7
30 7
31 6
32 6
33 6
34 4
35 4
36 4
37 4
38 3
39 3
40 3
41 3
42 2
43 1
44 1